dist: trusty
env:
  - GHCVER=7.10.3 CABALVER=1.22
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
install:
  - cabal update
  - cabal install --only-dependencies
script:
  - cabal build
